# [dein.toml]
[[plugins]]
repo = 'Shougo/dein.vim'

#################### ファイル検索 #################### 

# fzf-preview
# ripgrepをインストールするべし
[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'
rev = 'release/rpc'
depends=['junegunn/fzf']
hook_add= '''
source ~/.config/nvim/plugins/fzf-preview.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

#################### 見た目 #################### 
# インデントに線を表示する
[[plugins]]
repo = 'Yggdroot/indentLine'

# シンタックスハイライト
[[plugins]]
repo='sheerun/vim-polyglot'

# ---------- Vim Airline ---------- 
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.vim
'''

# vim-airlineのテーマ
[[plugins]]
repo = 'vim-airline/vim-airline-themes'


#################### Git #################### 
# Gitコマンドを使用する
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <silent> gs :Git status<CR>
nnoremap <silent> gps :Git push<CR>
nnoremap <silent> gpl :Git pull<CR>
nnoremap <silent> gc :Git commit<CR>
'''

# show add/delete sign to left
[[plugins]]
repo = 'airblade/vim-gitgutter'

# #################### Uncategorized ###################

# 対となる括弧を追加/削除する
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

# カッコを自動で補完
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
source ~/.config/nvim/plugins/vim-closetag.vim
'''

#################### 画像生成 #################### 

# ソースコードをいい感じの画像にしてくれる
[[plugins]]
repo = 'skanehira/denops-germanium.vim'
depends = ['denops.vim']
hook_add = '''
nnoremap <Leader>pic :Germanium<CR>
vnoremap <Leader>pic :Germanium<CR>
'''

[[plugins]]
repo = 'vim-denops/denops.vim'


