# [dein_lazy.toml]


# hook_add : deinによってプラグインが認識されたとき
# hook_source : プラグインを読み込む直前に
# hook_post_source : プラグインを読み込んだ直後


# on_i : インサートモードに入ったら読み込む
# on_ft : 特定のファイルタイプで読み込む
# on_func : 関数が事項されるときにロード
# on_event :  イベントが実行されるときにロード
# on_cmd : 

#################### エクスプローラー #################### 

# ファイルツリーを表示
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add='''
nnoremap <silent> <Leader>e :Fern . -drawer -toggle<CR>
'''

#################### 画面サイズ変更 #################### 

# ウィンドウの分割サイズを変更
[[plugins]]
repo = 'simeji/winresizer'
on_event='WinResizerStartResize'
hook_add='''
nnoremap <Leader>r :WinResizerStartResize<CR>
'''
#################### Quick Run #################### 

# vimを閉じずに編集中のファイルを素早く実行する
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/.config/nvim/plugins/vim-quickrun.vim
'''

# quick runに必要なライブラリ(非同期処理)
[[plugins]]
repo = 'Shougo/vimproc.vim'

#################### 言語ごとの設定 #################### 

# ---------- c++ ---------- 
[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'
on_ft = ['c', 'cpp']
hook_add = '''
nmap <leader>dox :Dox<CR>
'''

# ---------- Python ---------- 
[[plugins]]
repo = 'heavenshell/vim-pydocstring'
build='make install'
on_ft = ['python']
hook_add= '''
source ~/.config/nvim/plugins/vim-pydocstring.vim
'''

# ---------- TOML ---------- 
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']



