# [dein.toml]
[[plugins]]
repo = 'Shougo/dein.vim'


#############################
# 自動補完
#############################
#[[plugins]]
#repo = 'https://github.com/Shougo/ddc.vim'
#hook_source = '''
#source ~/.config/nvim/plugins/ddc.vim
#'''
#
#[[plugins]]
#repo = 'https://github.com/Shougo/pum.vim'
#hook_source = '''
#source ~/.config/nvim/plugins/pum.vim
#'''

#################### ファイル検索 #################### 

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'https://github.com/nvim-telescope/telescope.nvim'
rev = '0.1.x'
hook_add = '''
source ~/.config/nvim/plugins/telescope.vim
'''

## fzf-preview
## ripgrepをインストールするべし
#[[plugins]]
#repo = 'yuki-yano/fzf-preview.vim'
#rev = 'release/rpc'
#depends=['junegunn/fzf']
#hook_add= '''
#source ~/.config/nvim/plugins/fzf-preview.vim
#'''
#
#[[plugins]]
#repo = 'junegunn/fzf'
#build = './install --all'
#merged = 0

#################### 見た目 #################### 
# インデントに線を表示する
[[plugins]]
repo = 'Yggdroot/indentLine'

# シンタックスハイライト
[[plugins]]
repo='sheerun/vim-polyglot'
hook_add= '''
let g:polyglot_disabled = ['markdown']
'''

# ---------- Vim Airline ---------- 
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.vim
'''

# vim-airlineのテーマ
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#################### colorscheme #################### 
[[plugins]]
repo='morhetz/gruvbox'

[[plugins]]
repo='folke/tokyonight.nvim'

#################### Git #################### 
# Gitコマンドを使用する
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nnoremap <silent> gs :Git status<CR>
nnoremap <silent> gps :Git push<CR>
nnoremap <silent> gpl :Git pull<CR>
nnoremap <silent> gc :Git commit<CR>
'''

# show add/delete sign to left
[[plugins]]
repo = 'airblade/vim-gitgutter'

# git blame
[[plugins]]
repo = 'APZelos/blamer.nvim'

# #################### Uncategorized ###################

# 対となる括弧を追加/削除する
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# coc
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

# カッコを自動で補完
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
source ~/.config/nvim/plugins/vim-closetag.vim
'''

# importをいい感じに
[[plugins]]
repo = 'https://github.com/wookayin/vim-autoimport'
hook_add = '''
nnoremap <Leader>im :ImportSymbol<CR>
'''

#################### 画像生成 #################### 

# ソースコードをいい感じの画像にしてくれる
[[plugins]]
repo = 'skanehira/denops-germanium.vim'
depends = ['denops.vim']
hook_add = '''
nnoremap <Leader>pic :Germanium -f=RictyDiminished-Regular<CR>
vnoremap <Leader>pic :Germanium -f=RictyDiminished-Regular<CR>
'''

[[plugins]]
repo = 'vim-denops/denops.vim'


