#!/bin/zsh
# シェルスクリプトでもインタラクティブシェルでも必要な設定を書く

#--------------------------------------------------------------
#               Linux Configuration
#--------------------------------------------------------------


# -をつけると、左側の環境変数が指定されていた場合はそちらを優先する
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:=$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"

export PAGER=less

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

#--------------------------------------------------------------
#               Zsh Configuration
#--------------------------------------------------------------

export Z_DOT_DIR=$HOME
export Z_HOME_DIR=${XDG_CONFIG_HOME}/zsh
export Z_RC_DIR=$Z_HOME_DIR/rc
export Z_DATA_DIR=${Z_HOME_DIR}/

# /etc/zprofile を読み込まない
setopt no_global_rcs

if [ -f "$Z_DOT_DIR/.zshenv.local" ]; then
    source "$Z_DOT_DIR/.zshenv.local"
fi

#--------------------------------------------------------------
#               Third-party Software Configuration
#--------------------------------------------------------------


export CC=/usr/bin/clang-14
export CXX=/usr/bin/clang++-14
export PATH=$HOME/.robotech/bin:$PATH


# linuxbrew
test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# conda
source ${HOME}/anaconda3/etc/profile.d/conda.sh

# direnv
eval "$(direnv hook zsh)"

# nodejs
export PATH="$(brew --prefix)/opt/node@16/bin:$PATH"
export LDFLAGS="-L$(brew --prefix)/opt/node@16/lib"
export CPPFLAGS="-I$(brew --prefix)/opt/node@16/include"

# gcm core
export GPG_TTY=$(tty)

echo "~/.zshenv done"

