#!/bin/bash

function insert_path() {
    for N in "${@}";
    do
        export PATH=$N:$PATH
    done
}
function append_path() {
    for N in "${@}";
    do
        export PATH=$PATH:$N
    done
}

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

export LANG=ja_JP.UTF-8 # 日本語を使用
export LESSCHARSET=utf-8
#eval $(/usr/bin/locale-check C.UTF-8) # ""の中に日本語を入力すると文字化けする問題対策

append_path /usr/local/go/bin
append_path $HOME/bin
append_path $HOME/.robotech/bin


export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/x86_64-linux-gnu/pkgconfig/:/usr/share/pkgconfig

export PIPENV_VENV_IN_PROJECT=true
export PYENV_ROOT="$HOME/.pyenv"
insert_path $PYENV_ROOT/bin
eval "$(pyenv init --path)"

append_path usr/local/cuda/bin
export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
append_path $HOME/.nodebrew/current/bin
append_path /home/linuxbrew/.linuxbrew/opt/clang-format/bin

if [ -e '/opt/openMPI/' ]; then
    append_path /opt/openMPI/bin
    export LD_LIBRARY_PATH="/opt/openMPI/lib:$LD_LIBRARY_PATH"
    export MANPATH="/opt/openMPI/share/man:$MANPATH"
fi

if [ -e '/opt/relion4.0/' ]; then
    append_path /opt/relion4.0/bin/
fi

if [ -e '/opt/relion3.0/' ]; then
    append_path /opt/relion3.0/bin/
fi

# for wsl, secret service will not work without this command
eval `dbus-launch --sh-syntax`
