#!/bin/zsh
# インタラクティブシェルでのみ必要な設定を書く

#--------------------------------------------------------------
#               Third-party Software Configuration
#--------------------------------------------------------------

# linuxbrew
test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# nodejs
export PATH="$(brew --prefix)/opt/node@16/bin:$PATH"
export LDFLAGS="-L$(brew --prefix)/opt/node@16/lib"
export CPPFLAGS="-I$(brew --prefix)/opt/node@16/include"

# direnv
eval "$(direnv hook zsh)"

#--------------------------------------------------------------
#               Local Configuration
#--------------------------------------------------------------

if [ -f "$Z_DOT_DIR/.zshrc.local" ]; then
    source "$Z_DOT_DIR/.zshrc.local"
fi


#--------------------------------------------------------------
#               Base Configuration
#--------------------------------------------------------------

source "$Z_RC_DIR/base.zsh"

#--------------------------------------------------------------
#               Option
#--------------------------------------------------------------

source "$Z_RC_DIR/option.zsh"

#--------------------------------------------------------------
#               Completion
#--------------------------------------------------------------

source "$Z_RC_DIR/completion.zsh"

#--------------------------------------------------------------
#               Prompt Configuration
#--------------------------------------------------------------

source "$Z_RC_DIR/prompt.zsh"

#--------------------------------------------------------------
#               Alias
#--------------------------------------------------------------

source "$Z_RC_DIR/alias.zsh"


#--------------------------------------------------------------
#               Plugin
#--------------------------------------------------------------

source "$Z_RC_DIR/plugin.zsh"

#--------------------------------------------------------------
#               Bind key
#--------------------------------------------------------------

source "$Z_RC_DIR/bind_key.zsh"


echo "zshrc done"
