#!/bin/zsh
# シェルスクリプトでもインタラクティブシェルでも必要な設定を書く

#--------------------------------------------------------------
#               Linux Configuration
#--------------------------------------------------------------


# -をつけると、左側の環境変数が指定されていた場合はそちらを優先する
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:=$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"

export PAGER=less

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

#--------------------------------------------------------------
#               Zsh Configuration
#--------------------------------------------------------------

export Z_DOT_DIR=$HOME
export Z_HOME_DIR=${XDG_CONFIG_HOME}/zsh
export Z_RC_DIR=$Z_HOME_DIR/rc
export Z_DATA_DIR=${Z_HOME_DIR}/

# /etc/zprofile を読み込まない
setopt no_global_rcs

if [ -f "$Z_DOT_DIR/.zshenv.local" ]; then
    source "$Z_DOT_DIR/.zshenv.local"
fi

#--------------------------------------------------------------
#               Third-party Software Configuration
#--------------------------------------------------------------

export PATH=$PATH:$HOME/.pyenv/bin
eval "$(pyenv init --path)"
eval "$(direnv hook zsh)"

