#eval "$(${HOME}/.linuxbrew/bin/brew shellenv)"

#if type tmux > /dev/null 2>&1; then
#    UNATTACHED_LIST=$(tmux ls | grep -v attached | head -n 1)
#    UNATTACHED_ID=${UNATTACHED_LIST%%:*}
#    if [ -z "$TMUX" ]; then
#        if [ -n "$UNATTACHED_ID" ]; then
#            tmux a -t $UNATTACHED_ID
#        else
#            tmux
#        fi
#    fi
#fi
