format = """
[┌───────────────────>](bold green)
[│](bold green)$hostname$directory$rust$package$git_branch$git_metrics$memory_usage$cmake
[└─>](bold green) """
scan_timeout = 10
# シェルプロンプトの間に空行を追加
add_newline = true
command_timeout = 1000

[hostname]
ssh_only = false
format = "on [$hostname](bold red) "
trim_at='.'

[character]
# ">"記号を"→"記号に置き換える
success_symbol = "[➜](bold green)" # "success_symbol" セグメントが「太字の緑色」スタイルの "➜" に設定されています
error_symbol = "[❌](bold red)"

[directory]
# フルパスのほうが見やすい
truncation_length = 100
truncate_to_repo = false
truncation_symbol = ".../"

[git_metrics]
disabled = false

# packageモジュールを無効にし、プロンプトから完全に隠す
[package]
disabled = true

[memory_usage]
disabled = false
threshold = -1
symbol = "💻"
style = "bold dimmed blue"
format = "$symbol [${ram}]($style) "
